src/CoreBundle/Form/BranchType.php
<?php
/* For licensing terms, see /license.txt */

namespace Chamilo\CoreBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class BranchType extends AbstractType
{
    /**
     * Builds the form
     * For form type details see:
     * http://symfony.com/doc/current/reference/forms/types.html.
     *
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builderData = $builder->getData();

        $parentIdDisabled = false;
        if (!empty($builderData)) {
            $parentIdDisabled = true;
        }

        $builder
            ->add('branch_name', 'text')
            ->add(
                'branch_type',
                'choice',
                [
                    'choices' => [
                        'remote_child',
                        'local_child',
                        'local_parent',
                        'remote_parent',
                    ],
                ]
            )
            //->add('parent_id', 'choice', array('choices'=> array(), 'required' => false))
            ->add(
                'parent_id',
                'text',
                ['required' => false, 'disabled' => $parentIdDisabled]
            )
            //->add('parent_id', 'choice', array('choices'=> array(1 => 'jjaa',2=>'ddd'), 'required' => false))
            ->add('branch_ip', 'text')
            ->add('latitude', 'text')
            ->add('longitude', 'text')
            ->add('dwn_speed', 'text')
            ->add('up_speed', 'text')
            ->add('longitude', 'text')
            ->add('delay', 'text')
            ->add('admin_mail', 'email')
            ->add('admin_name', 'text')
            ->add('admin_phone', 'text', ['required' => false])
            ->add(
                'last_sync_trans_date',
                'datetime',
                [
                    'data' => new \DateTime(),
                ]
            )
            ->add('last_sync_type', 'text')
            ->add('last_sync_trans_id', 'text')
            ->add('ssl_pub_key', 'text')
            ->add('last_sync_trans_id', 'text')
            ->add('access_url_id', 'text')
            ->add('submit', 'submit');
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => 'Chamilo\CoreBundle\Entity\BranchSync',
            ]
        );
    }

    public function getName()
    {
        return 'branch';
    }
}

src/CoreBundle/Controller/UserController.php
<?php
/* For licensing terms, see /license.txt */

namespace Chamilo\CoreBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class UserController.
 *
 * @Route("/user")
 *
 * @author Julio Montoya <gugli100@gmail.com>
 */
class UserController extends BaseController
{
    /**
     * @Route("/{username}", methods={"GET"})
     *
     * @param string $username
     *
     * @Template("ChamiloCoreBundle:User:profile.html.twig")
     *
     * @return array
     */
    public function profileAction($username): array
    {
        $user = $this->container->get('fos_user.user_manager')->findUserByUsername($username);

        return ['user' => $user];
    }
}

src/CoreBundle/Resources/views/User/_form.html.twig
{% form_theme form '@ChamiloTheme/User/forms.html.twig' %}

{{ form_errors(form) }}
{% include '@ChamiloTheme/User/Form/_tabs.html.twig' %}
<br>
<div class="tab-content">
    {% include '@ChamiloTheme/User/Form/_main.html.twig' %}
    {% include '@ChamiloTheme/User/Form/_attributes.html.twig' %}
</div>
<hr>

{{ form_widget(form._token) }}

src/CoreBundle/Resources/views/User/create.html.twig
{% from '@ChamiloTheme/Macros/actions.html.twig' import create %}

{{ form_errors(form) }}

<form action="{{ url }}" method="post"
      class="form-horizontal" {{ form_enctype(form) }} novalidate>
    {% include '@ChamiloTheme/User/_form.html.twig' %}
    {{ create(url) }}
</form>

src/CoreBundle/Resources/views/User/forms.html.twig
{% extends 'form_div_layout.html.twig' %}

{% block choice_widget_collapsed %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
    {{ parent() }}
{% endblock choice_widget_collapsed %}

{% block textarea_widget %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
    {{ parent() }}
{% endblock textarea_widget %}

{% block form_widget_simple %}
    {% spaceless %}
        {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
        {% set type = type|default('text') %}

        {% if 'file' == type %}
            <span class="btn-primary btn-lg file-overlay"><i
                        class="icon-folder-open"></i> {{ 'sylius.form.choose_file'|trans }}</span>
        {% endif %}
        {{ parent() }}
    {% endspaceless %}
{% endblock form_widget_simple %}

{% block form_label %}
    {% spaceless %}
        {% set label_attr = label_attr|merge({'class': label_attr.class|default('col-lg-2') ~ ' control-label'}) %}
        {{ parent() }}
    {% endspaceless %}
{% endblock form_label %}

{% block money_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon">{{ money_pattern|replace({'{{ widget }}': ''}) }}</span>
            {{ block('form_widget_simple') }}
        </div>
    {% endspaceless %}
{% endblock money_widget %}

{% block percent_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon">%</span>
            {{ block('form_widget_simple') }}
        </div>
    {% endspaceless %}
{% endblock percent_widget %}

{% block datetime_widget %}
    {% spaceless %}
        {% if widget == 'single_text' %}
            {{ block('form_widget_simple') }}
        {% else %}
            <div class="form-group">
                {{ form_widget(form.date) }}
                {{ form_widget(form.time) }}
            </div>
        {% endif %}
    {% endspaceless %}
{% endblock datetime_widget %}

{% block date_widget %}
    {% spaceless %}
        {% if widget == 'single_text' %}
            {{ block('form_widget_simple') }}
        {% else %}
            {{ '{{ year }} / {{ month }} / {{ day }}'|replace({
                '{{ year }}':  form_widget(form.year, {'attr': {'style': 'display: inline; width: 100px;'}}),
                '{{ month }}': form_widget(form.month, {'attr': {'style': 'display: inline; width: 100px;'}}),
                '{{ day }}':   form_widget(form.day, {'attr': {'style': 'display: inline; width: 100px;'}}),
            })|raw }}
        {% endif %}
    {% endspaceless %}
{% endblock date_widget %}

{% block time_widget %}
    {% spaceless %}
        {% if widget == 'single_text' %}
            {{ block('form_widget_simple') }}
        {% else %}
            {% set vars = widget == 'text' ? { 'attr': { 'size': 1, 'style': 'width: 60px; display: inline;' }} : {} %}
            &nbsp;{{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %} {{ form_widget(form.second, vars) }}{% endif %}
        {% endif %}
    {% endspaceless %}
{% endblock time_widget %}

{% block form_row %}
    {% spaceless %}
        <div class="form-group{% if errors|length > 0 %} has-error{% endif %}">
            {{ form_label(form) }}
            <div class="col-lg-10">
                {{ form_widget(form) }}
                {% for error in errors %}
                    <span class="help-block form-error">
                {{ error.messagePluralization is null
                ? error.messageTemplate|trans(error.messageParameters, 'validators')
                : error.messageTemplate|transchoice(error.messagePluralization, error.messageParameters, 'validators') }}
            </span>
                {% endfor %}
            </div>
        </div>
    {% endspaceless %}
{% endblock form_row %}

{% block sonata_media_type_widget %}
    <div class="col-xs-3 pull-left">
        {% if value is not empty and value.providerReference %}
            <div class="pull-left" style="margin-right: 5px">
                {% thumbnail value, 'admin' with {'class': 'img-polaroid media-object'} %}
            </div>

            {% if sonata_admin_enabled is defined and sonata_admin_enabled %}
                <a href="{{ url('admin_sonata_media_media_edit', {id: value.id}) }}"><strong>{{ value.name }}</strong></a>
            {% else %}
                <strong>{{ value.name }}</strong>
            {% endif %}
            <br/>
            <span type="label">{{ value.providerName|trans({}, 'SonataMediaBundle') }}</span> ~ {{ value.context }}
        {% else %}
            <div class="pull-left" style="margin-right: 5px">
                <img src="{{ asset('bundles/sonatamedia/grey.png') }}"
                     class="img-polaroid media-object"
                     style="width: 85px; height: 85px"/>
            </div>
            <strong>{{ 'no_linked_media'|trans({}, 'SonataMediaBundle') }}</strong>
            <br/>
            <span type="label">{{ form.vars['provider']|trans({}, 'SonataMediaBundle') }}
                ~ {{ form.vars['context']|trans({}, 'SonataMediaBundle') }}</span>
        {% endif %}
    </div>

    <div class="span3 pull-left">
        {{ 'link_media'|trans({}, 'SonataMediaBundle') }}
        {{ block('form_widget') }}
    </div>
{% endblock sonata_media_type_widget %}

src/CoreBundle/Resources/views/User/profile.html.twig
{% extends "@ChamiloTheme/Layout/layout_one_col.html.twig" %}

{% block content %}
    {% autoescape false %}
        <h3>{{ user.username }}</h3>
        {{ user.firstname }}
        {{ user.lastname }}
        {{ user.competences }}
        {{ user.openarea }}
        {{ user.teach }}


        {{ user.diplomas }}

    {% endautoescape %}
{% endblock %}